document.writeln("<!-- 横线 -->");
document.writeln("<hr>");
document.writeln("<!-- 页脚 -->");
document.writeln("<footer class=\'container-fluid foot-wrap\'>");
document.writeln("  <div class=\'container\'>");
document.writeln("    <center>");
document.writeln("        ver v0.1 <br />");
document.writeln("        Powered by Late Lee <span>&copy;</span> <span><script>document.write(new Date().getFullYear());</script></span>");
document.writeln("    </center>");
document.writeln("  </div>");
document.writeln("</footer>");