document.writeln("<header class=\'post-header\'>");
document.writeln("	<center>");
document.writeln("        <div class=\'contact-title\'>叠加器管理后台</div>");
document.writeln("		<div class=\'contact-subtitle\'><p> boa+html+js+cgi+onvif </p></div>");
document.writeln("    </center>");
document.writeln("</header>");
document.writeln("");
document.writeln("<div class=\'container\'>");
document.writeln("    <div class=\'col-md-2\'>");
document.writeln("    </div>");
document.writeln("    <div class=\'col-md-8\'>");
document.writeln("      <ul class=\'nav nav-tabs\'>");
document.writeln("          <li><a class=\'link\' href=\'index.html\'>首页</a></li>");
document.writeln("          <li><a class=\'link\' href=\'login.html\'>登陆</a></li>");
document.writeln("          <li><a class=\'link\' href=\'address.html\'>地址配置</a></li>");
document.writeln("          <li><a class=\'link\' href=\'cameraset.html\'>摄像头配置</a></li>");
document.writeln("          <li><a class=\'link\' href=\'location.html\'>位置配置</a></li>");
document.writeln("          <li><a class=\'link\' href=\'account.html\'>账号配置</a></li>");
document.writeln("          <li><a class=\'link\' href=\'camerascan.html\'>摄像头扫瞄</a></li>");
document.writeln("          <li><a class=\'link\' href=\'about.html\'>系统</a></li>");
document.writeln("    </div>");
document.writeln("</div>");